// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/team.go

// Package storage is a generated GoMock package.
package storage

import (
	models "pr_reviewer/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamStorage is a mock of TeamStorage interface.
type MockTeamStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTeamStorageMockRecorder
}

// MockTeamStorageMockRecorder is the mock recorder for MockTeamStorage.
type MockTeamStorageMockRecorder struct {
	mock *MockTeamStorage
}

// NewMockTeamStorage creates a new mock instance.
func NewMockTeamStorage(ctrl *gomock.Controller) *MockTeamStorage {
	mock := &MockTeamStorage{ctrl: ctrl}
	mock.recorder = &MockTeamStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamStorage) EXPECT() *MockTeamStorageMockRecorder {
	return m.recorder
}

// AddTeam mocks base method.
func (m *MockTeamStorage) AddTeam(team models.Team) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", team)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTeam indicates an expected call of AddTeam.
func (mr *MockTeamStorageMockRecorder) AddTeam(team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*MockTeamStorage)(nil).AddTeam), team)
}

// DeactivateTeam mocks base method.
func (m *MockTeamStorage) DeactivateTeam(team models.Team) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTeam", team)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateTeam indicates an expected call of DeactivateTeam.
func (mr *MockTeamStorageMockRecorder) DeactivateTeam(team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTeam", reflect.TypeOf((*MockTeamStorage)(nil).DeactivateTeam), team)
}

// GetTeam mocks base method.
func (m *MockTeamStorage) GetTeam(teamName string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", teamName)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamStorageMockRecorder) GetTeam(teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamStorage)(nil).GetTeam), teamName)
}
