// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/pull_request.go

// Package storage is a generated GoMock package.
package storage

import (
	models "pr_reviewer/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPRStorage is a mock of PRStorage interface.
type MockPRStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPRStorageMockRecorder
}

// MockPRStorageMockRecorder is the mock recorder for MockPRStorage.
type MockPRStorageMockRecorder struct {
	mock *MockPRStorage
}

// NewMockPRStorage creates a new mock instance.
func NewMockPRStorage(ctrl *gomock.Controller) *MockPRStorage {
	mock := &MockPRStorage{ctrl: ctrl}
	mock.recorder = &MockPRStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRStorage) EXPECT() *MockPRStorageMockRecorder {
	return m.recorder
}

// CreatePullRequest mocks base method.
func (m *MockPRStorage) CreatePullRequest(pullRequestID, pullRequestName, authorID string) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", pullRequestID, pullRequestName, authorID)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockPRStorageMockRecorder) CreatePullRequest(pullRequestID, pullRequestName, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockPRStorage)(nil).CreatePullRequest), pullRequestID, pullRequestName, authorID)
}

// MergePullRequest mocks base method.
func (m *MockPRStorage) MergePullRequest(pullRequestID string) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", pullRequestID)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockPRStorageMockRecorder) MergePullRequest(pullRequestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockPRStorage)(nil).MergePullRequest), pullRequestID)
}

// ReasignReviewer mocks base method.
func (m *MockPRStorage) ReasignReviewer(pullRequestID, oldReviewerID string) (*models.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReasignReviewer", pullRequestID, oldReviewerID)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReasignReviewer indicates an expected call of ReasignReviewer.
func (mr *MockPRStorageMockRecorder) ReasignReviewer(pullRequestID, oldReviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReasignReviewer", reflect.TypeOf((*MockPRStorage)(nil).ReasignReviewer), pullRequestID, oldReviewerID)
}
